Attempt to pull the latest doc generation stuff from hylo

diff --git a/.github/workflows/doc-extraction.yml b/.github/workflows/doc-extraction.yml
--- a/.github/workflows/doc-extraction.yml
+++ b/.github/workflows/doc-extraction.yml
@@ -2,7 +2,7 @@ name: Extract And Publish Documentation
 
 defaults:
   run:
-    shell: bash -eo pipefail {0}
+    shell: 'bash -eo pipefail {0}'
 
 on:
   push:
@@ -24,69 +24,83 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
-  # Build job
   build:
     if: github.repository == 'hylo-lang/Lotsawa'
     runs-on: macos-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Make site Directory
-        run: mkdir -p _site/docc
-      - name: Prepare Shell Environment
-        # The format of the ${GITHUB_ENV} file is extremely restrictive; it apparently only supports
-        # lines of the form:
-        #
-        #   <variable-name>=<one-line-of-text>
-        #
-        # And a multiline version
-        # (https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings).
-        # It is not interpreted directly by a shell, so any quotes or other special characters are
-        # taken literally.
+    - uses: actions/checkout@v4
+      with:
+        submodules: true
+        show-progress: false
 
-        # FIXME: REF_URL_COMPONENT computation is probably wrong for some refs.
-        run: |
-          echo "REPO_SANS_OWNER=${GITHUB_REPOSITORY##*/}
-          REF_URL_COMPONENT=${GITHUB_REF##*/}
-          " >> "${GITHUB_ENV}"
+    - name: Make site Directory
+      run: mkdir -p _site/docc
 
-      - name: Run DocC
-        run: |
-          swift package --allow-writing-to-directory ./_site \
-          generate-documentation \
-          --product Lotsawa \
-          --output-path _site/docc \
-          --experimental-documentation-coverage --level detailed \
-          --enable-inherited-docs \
-          --transform-for-static-hosting \
-          --hosting-base-path "${REPO_SANS_OWNER}/docc/${TARGET}" \
-          --source-service github \
-          --source-service-base-url "https://github.com/${GITHUB_REPOSITORY}/blob/${REF_URL_COMPONENT}" \
-          --checkout-path "$(pwd)"
-      - name: Install jazzy
-        run: gem install jazzy
-      - name: Run Jazzy
-        run: |
-          jazzy \
-          --source-host-files-url "https://github.com/${GITHUB_REPOSITORY}/blob/${REF_URL_COMPONENT}" \
-          --module Lotsawa \
-          --module-version "${{ github.event.release.tag_name }}" \
-          --copyright "© $(date '+%Y') Dave Abrahams. (Last updated: $(date '+%Y-%m-%d'))" \
-          --config .jazzy.yml \
-          --output _site/jazzy \
-          --min-acl private
+    - name: Install Jazzy
+      run: |
+        gem install jazzy
 
-      - name: Setup Pages
-        uses: actions/configure-pages@v3
+    - name: Setup swift
+      uses: swift-actions/setup-swift@v1
+      with:
+        swift-version: 5.9
 
-      - name: Fix permissions
-        run: |
-          chmod -v -R +rX "_site/" | while read line; do
-            echo "::warning title=Invalid file permissions automatically fixed::$line"
-          done
+    - name: Prepare Shell Environment
+      # The format of the ${GITHUB_ENV} file is extremely restrictive; it apparently only supports
+      # lines of the form:
+      #
+      #   <variable-name>=<one-line-of-text>
+      #
+      # And a multiline version
+      # (https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings).
+      # It is not interpreted directly by a shell, so any quotes or other special characters are
+      # taken literally.
 
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v2
+      # FIXME: REF_URL_COMPONENT computation is probably wrong for some refs.
+      run: |
+        echo "REPO_SANS_OWNER=${GITHUB_REPOSITORY##*/}
+        REF_URL_COMPONENT=${GITHUB_REF##*/}
+        LOTSAWA_ENABLE_DOC_GENERATION=1
+        " >> "${GITHUB_ENV}"
+
+    - name: Extract with DocC
+      run: |
+        mkdir -p _site/docc
+        swift package --allow-writing-to-directory ./_site \
+        generate-documentation \
+        --product Lotsawa \
+        --output-path _site/docc \
+        --experimental-documentation-coverage --level detailed \
+        --enable-inherited-docs \
+        --transform-for-static-hosting \
+        --hosting-base-path "${REPO_SANS_OWNER}/docc/${TARGET}" \
+        --source-service github \
+        --source-service-base-url "https://github.com/${GITHUB_REPOSITORY}/blob/${REF_URL_COMPONENT}" \
+        --checkout-path "$(pwd)"
+
+    - name: Extract with Jazzy
+      run: |
+        mkdir -p _site/jazzy
+        jazzy \
+        --source-host-files-url "https://github.com/${GITHUB_REPOSITORY}/blob/${REF_URL_COMPONENT}" \
+        --module Lotsawa \
+        --module-version "${{ github.event.release.tag_name }}" \
+        --copyright "© $(date '+%Y') Dave Abrahams. (Last updated: $(date '+%Y-%m-%d'))" \
+        --config .jazzy.yml \
+        --output _site/jazzy \
+        --min-acl private
+
+    - name: Setup Pages
+      uses: actions/configure-pages@v3
+
+    - name: Fix permissions
+      run: |
+        chmod -v -R +rX "_site/" | while read line; do
+          echo "::warning title=Invalid file permissions automatically fixed::$line"
+        done
+
+    - name: Upload artifact
+      uses: actions/upload-pages-artifact@v2
 
   # Deployment job
   deploy:
